# ------------------------------------------------------------------------------
# This is a configuration file for the pull-gui.sh script, for more see:
#   _build/default/lib/gui/pull-gui.sh
#
# The pull-gui.sh script fetches a GUI package (static files) and places it in
# deps directory (see pull-gui.sh -> TARGET_PATH). The package must be moved to
# the target location during release generation (usually done in rebar.config).
# The script attempts to download specified docker image from two repositories:
# docker.onedata.org (primary) or dockerhub (fallback).
# ------------------------------------------------------------------------------

# The name of the docker image containing the GUI package.
IMAGE_NAME="onepanel-gui"
# Tag (version) of the above image.
IMAGE_TAG="ID_SHA256P-12df4eed09-fc2dbdf3fa"
# SHA-256 checksum of the GUI package (tar.gz archive) embedded in the docker.
# Used for additional integrity check and to keep track of verified GUI packages.
PACKAGE_CHECKSUM="fc2dbdf3faebfee7a1b25ac2848f88651f7db9c64171b51b75648bf99d1a9517"
