%%%-------------------------------------------------------------------
%%% This file has been automatically generated - DO NOT EDIT!!!
%%%
%%% @copyright (C) 2025 Onedata (onedata.org)
%%% This software is released under the MIT license
%%% cited in 'LICENSE.txt'.
%%% @end
%%%-------------------------------------------------------------------
%%% @doc
%%% This module contains aggregated types for behaviour: middleware_handler.
%%% @end
%%%-------------------------------------------------------------------
-module(middleware_handler_types).

-type t() ::
    cluster_current_cluster_get_middleware_handler:t() |
    cluster_current_cluster_members_summary_get_middleware_handler:t() |
    cluster_instance_get_middleware_handler:t() |
    cluster_invite_user_token_create_middleware_handler:t() |
    host_external_ips_get_middleware_handler:t() |
    host_external_ips_update_middleware_handler:t() |
    host_instance_create_middleware_handler:t() |
    host_instance_delete_middleware_handler:t() |
    host_instance_get_middleware_handler:t() |
    host_join_cluster_middleware_handler:t() |
    host_list_get_middleware_handler:t() |
    panel_configuration_get_middleware_handler:t() |
    panel_cookie_get_middleware_handler:t() |
    panel_dns_check_configuration_get_middleware_handler:t() |
    panel_dns_check_configuration_update_middleware_handler:t() |
    panel_dns_check_middleware_handler:t() |
    panel_emergency_passphrase_create_middleware_handler:t() |
    panel_emergency_passphrase_get_middleware_handler:t() |
    panel_health_get_middleware_handler:t() |
    panel_invite_token_create_middleware_handler:t() |
    panel_progress_get_middleware_handler:t() |
    panel_progress_update_middleware_handler:t() |
    panel_task_get_middleware_handler:t() |
    panel_test_image_get_middleware_handler:t() |
    panel_web_cert_get_middleware_handler:t() |
    panel_web_cert_update_middleware_handler:t() |
    provider_cluster_create_middleware_handler:t() |
    provider_cluster_get_middleware_handler:t() |
    provider_instance_create_middleware_handler:t() |
    provider_instance_delete_middleware_handler:t() |
    provider_instance_get_middleware_handler:t() |
    provider_instance_update_middleware_handler:t() |
    provider_remote_instance_get_middleware_handler:t() |
    provider_transfers_mock_get_middleware_handler:t() |
    provider_transfers_mock_update_middleware_handler:t() |
    service_cluster_manager_all_hosts_status_get_middleware_handler:t() |
    service_cluster_manager_host_status_get_middleware_handler:t() |
    service_cluster_manager_instances_create_middleware_handler:t() |
    service_cluster_manager_start_stop_all_update_middleware_handler:t() |
    service_cluster_manager_start_stop_update_middleware_handler:t() |
    service_couchbase_all_hosts_status_get_middleware_handler:t() |
    service_couchbase_host_status_get_middleware_handler:t() |
    service_couchbase_instances_create_middleware_handler:t() |
    service_couchbase_start_stop_all_update_middleware_handler:t() |
    service_couchbase_start_stop_update_middleware_handler:t() |
    service_ones3_all_hosts_status_get_middleware_handler:t() |
    service_ones3_host_status_get_middleware_handler:t() |
    service_ones3_instances_create_middleware_handler:t() |
    service_ones3_start_stop_all_update_middleware_handler:t() |
    service_ones3_start_stop_update_middleware_handler:t() |
    service_op_worker_all_hosts_status_get_middleware_handler:t() |
    service_op_worker_host_status_get_middleware_handler:t() |
    service_op_worker_instances_create_middleware_handler:t() |
    service_op_worker_nagios_get_middleware_handler:t() |
    service_op_worker_start_stop_all_update_middleware_handler:t() |
    service_op_worker_start_stop_update_middleware_handler:t() |
    service_oz_worker_all_hosts_status_get_middleware_handler:t() |
    service_oz_worker_host_status_get_middleware_handler:t() |
    service_oz_worker_instances_create_middleware_handler:t() |
    service_oz_worker_nagios_get_middleware_handler:t() |
    service_oz_worker_start_stop_all_update_middleware_handler:t() |
    service_oz_worker_start_stop_update_middleware_handler:t() |
    space_auto_cleaning_configuration_get_middleware_handler:t() |
    space_auto_cleaning_configuration_update_middleware_handler:t() |
    space_auto_cleaning_report_get_middleware_handler:t() |
    space_auto_cleaning_reports_list_get_middleware_handler:t() |
    space_auto_cleaning_status_get_middleware_handler:t() |
    space_auto_storage_import_info_get_middleware_handler:t() |
    space_auto_storage_import_stats_get_middleware_handler:t() |
    space_cancel_auto_cleaning_create_middleware_handler:t() |
    space_file_popularity_configuration_get_middleware_handler:t() |
    space_file_popularity_configuration_update_middleware_handler:t() |
    space_force_start_auto_storage_import_scan_create_middleware_handler:t() |
    space_force_stop_auto_storage_import_scan_create_middleware_handler:t() |
    space_instance_get_middleware_handler:t() |
    space_list_get_middleware_handler:t() |
    space_manual_storage_import_example_get_middleware_handler:t() |
    space_start_auto_cleaning_create_middleware_handler:t() |
    space_support_create_middleware_handler:t() |
    space_support_delete_middleware_handler:t() |
    space_support_update_middleware_handler:t() |
    storage_instance_delete_middleware_handler:t() |
    storage_instance_get_middleware_handler:t() |
    storage_instance_update_middleware_handler:t() |
    storage_instances_create_middleware_handler:t() |
    storage_list_get_middleware_handler:t() |
    storage_luma_acl_group_to_onedata_group_mapping_create_middleware_handler:t() |
    storage_luma_acl_group_to_onedata_group_mapping_delete_middleware_handler:t() |
    storage_luma_acl_group_to_onedata_group_mapping_get_middleware_handler:t() |
    storage_luma_acl_user_to_onedata_user_mapping_create_middleware_handler:t() |
    storage_luma_acl_user_to_onedata_user_mapping_delete_middleware_handler:t() |
    storage_luma_acl_user_to_onedata_user_mapping_get_middleware_handler:t() |
    storage_luma_configuration_get_middleware_handler:t() |
    storage_luma_db_delete_middleware_handler:t() |
    storage_luma_default_posix_credentials_create_middleware_handler:t() |
    storage_luma_default_posix_credentials_delete_middleware_handler:t() |
    storage_luma_default_posix_credentials_get_middleware_handler:t() |
    storage_luma_display_credentials_create_middleware_handler:t() |
    storage_luma_display_credentials_delete_middleware_handler:t() |
    storage_luma_display_credentials_get_middleware_handler:t() |
    storage_luma_onedata_user_to_credentials_mapping_create_middleware_handler:t() |
    storage_luma_onedata_user_to_credentials_mapping_delete_middleware_handler:t() |
    storage_luma_onedata_user_to_credentials_mapping_get_middleware_handler:t() |
    storage_luma_onedata_user_to_credentials_mapping_update_middleware_handler:t() |
    storage_luma_uid_to_onedata_user_mapping_create_middleware_handler:t() |
    storage_luma_uid_to_onedata_user_mapping_delete_middleware_handler:t() |
    storage_luma_uid_to_onedata_user_mapping_get_middleware_handler:t() |
    user_current_user_clusters_get_middleware_handler:t() |
    user_current_user_get_middleware_handler:t() |
    user_instance_create_middleware_handler:t() |
    user_instance_get_middleware_handler:t() |
    user_instance_update_middleware_handler:t() |
    user_list_get_middleware_handler:t() |
    zone_cluster_create_middleware_handler:t() |
    zone_cluster_get_middleware_handler:t() |
    zone_gui_message_get_middleware_handler:t() |
    zone_gui_message_update_middleware_handler:t() |
    zone_instance_get_middleware_handler:t() |
    zone_policies_get_middleware_handler:t() |
    zone_policies_update_middleware_handler:t().

-type input() ::
    cluster_current_cluster_get_middleware_handler:input() |
    cluster_current_cluster_members_summary_get_middleware_handler:input() |
    cluster_instance_get_middleware_handler:input() |
    cluster_invite_user_token_create_middleware_handler:input() |
    host_external_ips_get_middleware_handler:input() |
    host_external_ips_update_middleware_handler:input() |
    host_instance_create_middleware_handler:input() |
    host_instance_delete_middleware_handler:input() |
    host_instance_get_middleware_handler:input() |
    host_join_cluster_middleware_handler:input() |
    host_list_get_middleware_handler:input() |
    panel_configuration_get_middleware_handler:input() |
    panel_cookie_get_middleware_handler:input() |
    panel_dns_check_configuration_get_middleware_handler:input() |
    panel_dns_check_configuration_update_middleware_handler:input() |
    panel_dns_check_middleware_handler:input() |
    panel_emergency_passphrase_create_middleware_handler:input() |
    panel_emergency_passphrase_get_middleware_handler:input() |
    panel_health_get_middleware_handler:input() |
    panel_invite_token_create_middleware_handler:input() |
    panel_progress_get_middleware_handler:input() |
    panel_progress_update_middleware_handler:input() |
    panel_task_get_middleware_handler:input() |
    panel_test_image_get_middleware_handler:input() |
    panel_web_cert_get_middleware_handler:input() |
    panel_web_cert_update_middleware_handler:input() |
    provider_cluster_create_middleware_handler:input() |
    provider_cluster_get_middleware_handler:input() |
    provider_instance_create_middleware_handler:input() |
    provider_instance_delete_middleware_handler:input() |
    provider_instance_get_middleware_handler:input() |
    provider_instance_update_middleware_handler:input() |
    provider_remote_instance_get_middleware_handler:input() |
    provider_transfers_mock_get_middleware_handler:input() |
    provider_transfers_mock_update_middleware_handler:input() |
    service_cluster_manager_all_hosts_status_get_middleware_handler:input() |
    service_cluster_manager_host_status_get_middleware_handler:input() |
    service_cluster_manager_instances_create_middleware_handler:input() |
    service_cluster_manager_start_stop_all_update_middleware_handler:input() |
    service_cluster_manager_start_stop_update_middleware_handler:input() |
    service_couchbase_all_hosts_status_get_middleware_handler:input() |
    service_couchbase_host_status_get_middleware_handler:input() |
    service_couchbase_instances_create_middleware_handler:input() |
    service_couchbase_start_stop_all_update_middleware_handler:input() |
    service_couchbase_start_stop_update_middleware_handler:input() |
    service_ones3_all_hosts_status_get_middleware_handler:input() |
    service_ones3_host_status_get_middleware_handler:input() |
    service_ones3_instances_create_middleware_handler:input() |
    service_ones3_start_stop_all_update_middleware_handler:input() |
    service_ones3_start_stop_update_middleware_handler:input() |
    service_op_worker_all_hosts_status_get_middleware_handler:input() |
    service_op_worker_host_status_get_middleware_handler:input() |
    service_op_worker_instances_create_middleware_handler:input() |
    service_op_worker_nagios_get_middleware_handler:input() |
    service_op_worker_start_stop_all_update_middleware_handler:input() |
    service_op_worker_start_stop_update_middleware_handler:input() |
    service_oz_worker_all_hosts_status_get_middleware_handler:input() |
    service_oz_worker_host_status_get_middleware_handler:input() |
    service_oz_worker_instances_create_middleware_handler:input() |
    service_oz_worker_nagios_get_middleware_handler:input() |
    service_oz_worker_start_stop_all_update_middleware_handler:input() |
    service_oz_worker_start_stop_update_middleware_handler:input() |
    space_auto_cleaning_configuration_get_middleware_handler:input() |
    space_auto_cleaning_configuration_update_middleware_handler:input() |
    space_auto_cleaning_report_get_middleware_handler:input() |
    space_auto_cleaning_reports_list_get_middleware_handler:input() |
    space_auto_cleaning_status_get_middleware_handler:input() |
    space_auto_storage_import_info_get_middleware_handler:input() |
    space_auto_storage_import_stats_get_middleware_handler:input() |
    space_cancel_auto_cleaning_create_middleware_handler:input() |
    space_file_popularity_configuration_get_middleware_handler:input() |
    space_file_popularity_configuration_update_middleware_handler:input() |
    space_force_start_auto_storage_import_scan_create_middleware_handler:input() |
    space_force_stop_auto_storage_import_scan_create_middleware_handler:input() |
    space_instance_get_middleware_handler:input() |
    space_list_get_middleware_handler:input() |
    space_manual_storage_import_example_get_middleware_handler:input() |
    space_start_auto_cleaning_create_middleware_handler:input() |
    space_support_create_middleware_handler:input() |
    space_support_delete_middleware_handler:input() |
    space_support_update_middleware_handler:input() |
    storage_instance_delete_middleware_handler:input() |
    storage_instance_get_middleware_handler:input() |
    storage_instance_update_middleware_handler:input() |
    storage_instances_create_middleware_handler:input() |
    storage_list_get_middleware_handler:input() |
    storage_luma_acl_group_to_onedata_group_mapping_create_middleware_handler:input() |
    storage_luma_acl_group_to_onedata_group_mapping_delete_middleware_handler:input() |
    storage_luma_acl_group_to_onedata_group_mapping_get_middleware_handler:input() |
    storage_luma_acl_user_to_onedata_user_mapping_create_middleware_handler:input() |
    storage_luma_acl_user_to_onedata_user_mapping_delete_middleware_handler:input() |
    storage_luma_acl_user_to_onedata_user_mapping_get_middleware_handler:input() |
    storage_luma_configuration_get_middleware_handler:input() |
    storage_luma_db_delete_middleware_handler:input() |
    storage_luma_default_posix_credentials_create_middleware_handler:input() |
    storage_luma_default_posix_credentials_delete_middleware_handler:input() |
    storage_luma_default_posix_credentials_get_middleware_handler:input() |
    storage_luma_display_credentials_create_middleware_handler:input() |
    storage_luma_display_credentials_delete_middleware_handler:input() |
    storage_luma_display_credentials_get_middleware_handler:input() |
    storage_luma_onedata_user_to_credentials_mapping_create_middleware_handler:input() |
    storage_luma_onedata_user_to_credentials_mapping_delete_middleware_handler:input() |
    storage_luma_onedata_user_to_credentials_mapping_get_middleware_handler:input() |
    storage_luma_onedata_user_to_credentials_mapping_update_middleware_handler:input() |
    storage_luma_uid_to_onedata_user_mapping_create_middleware_handler:input() |
    storage_luma_uid_to_onedata_user_mapping_delete_middleware_handler:input() |
    storage_luma_uid_to_onedata_user_mapping_get_middleware_handler:input() |
    user_current_user_clusters_get_middleware_handler:input() |
    user_current_user_get_middleware_handler:input() |
    user_instance_create_middleware_handler:input() |
    user_instance_get_middleware_handler:input() |
    user_instance_update_middleware_handler:input() |
    user_list_get_middleware_handler:input() |
    zone_cluster_create_middleware_handler:input() |
    zone_cluster_get_middleware_handler:input() |
    zone_gui_message_get_middleware_handler:input() |
    zone_gui_message_update_middleware_handler:input() |
    zone_instance_get_middleware_handler:input() |
    zone_policies_get_middleware_handler:input() |
    zone_policies_update_middleware_handler:input().

-type state() ::
    cluster_current_cluster_get_middleware_handler:state() |
    cluster_current_cluster_members_summary_get_middleware_handler:state() |
    cluster_instance_get_middleware_handler:state() |
    cluster_invite_user_token_create_middleware_handler:state() |
    host_external_ips_get_middleware_handler:state() |
    host_external_ips_update_middleware_handler:state() |
    host_instance_create_middleware_handler:state() |
    host_instance_delete_middleware_handler:state() |
    host_instance_get_middleware_handler:state() |
    host_join_cluster_middleware_handler:state() |
    host_list_get_middleware_handler:state() |
    panel_configuration_get_middleware_handler:state() |
    panel_cookie_get_middleware_handler:state() |
    panel_dns_check_configuration_get_middleware_handler:state() |
    panel_dns_check_configuration_update_middleware_handler:state() |
    panel_dns_check_middleware_handler:state() |
    panel_emergency_passphrase_create_middleware_handler:state() |
    panel_emergency_passphrase_get_middleware_handler:state() |
    panel_health_get_middleware_handler:state() |
    panel_invite_token_create_middleware_handler:state() |
    panel_progress_get_middleware_handler:state() |
    panel_progress_update_middleware_handler:state() |
    panel_task_get_middleware_handler:state() |
    panel_test_image_get_middleware_handler:state() |
    panel_web_cert_get_middleware_handler:state() |
    panel_web_cert_update_middleware_handler:state() |
    provider_cluster_create_middleware_handler:state() |
    provider_cluster_get_middleware_handler:state() |
    provider_instance_create_middleware_handler:state() |
    provider_instance_delete_middleware_handler:state() |
    provider_instance_get_middleware_handler:state() |
    provider_instance_update_middleware_handler:state() |
    provider_remote_instance_get_middleware_handler:state() |
    provider_transfers_mock_get_middleware_handler:state() |
    provider_transfers_mock_update_middleware_handler:state() |
    service_cluster_manager_all_hosts_status_get_middleware_handler:state() |
    service_cluster_manager_host_status_get_middleware_handler:state() |
    service_cluster_manager_instances_create_middleware_handler:state() |
    service_cluster_manager_start_stop_all_update_middleware_handler:state() |
    service_cluster_manager_start_stop_update_middleware_handler:state() |
    service_couchbase_all_hosts_status_get_middleware_handler:state() |
    service_couchbase_host_status_get_middleware_handler:state() |
    service_couchbase_instances_create_middleware_handler:state() |
    service_couchbase_start_stop_all_update_middleware_handler:state() |
    service_couchbase_start_stop_update_middleware_handler:state() |
    service_ones3_all_hosts_status_get_middleware_handler:state() |
    service_ones3_host_status_get_middleware_handler:state() |
    service_ones3_instances_create_middleware_handler:state() |
    service_ones3_start_stop_all_update_middleware_handler:state() |
    service_ones3_start_stop_update_middleware_handler:state() |
    service_op_worker_all_hosts_status_get_middleware_handler:state() |
    service_op_worker_host_status_get_middleware_handler:state() |
    service_op_worker_instances_create_middleware_handler:state() |
    service_op_worker_nagios_get_middleware_handler:state() |
    service_op_worker_start_stop_all_update_middleware_handler:state() |
    service_op_worker_start_stop_update_middleware_handler:state() |
    service_oz_worker_all_hosts_status_get_middleware_handler:state() |
    service_oz_worker_host_status_get_middleware_handler:state() |
    service_oz_worker_instances_create_middleware_handler:state() |
    service_oz_worker_nagios_get_middleware_handler:state() |
    service_oz_worker_start_stop_all_update_middleware_handler:state() |
    service_oz_worker_start_stop_update_middleware_handler:state() |
    space_auto_cleaning_configuration_get_middleware_handler:state() |
    space_auto_cleaning_configuration_update_middleware_handler:state() |
    space_auto_cleaning_report_get_middleware_handler:state() |
    space_auto_cleaning_reports_list_get_middleware_handler:state() |
    space_auto_cleaning_status_get_middleware_handler:state() |
    space_auto_storage_import_info_get_middleware_handler:state() |
    space_auto_storage_import_stats_get_middleware_handler:state() |
    space_cancel_auto_cleaning_create_middleware_handler:state() |
    space_file_popularity_configuration_get_middleware_handler:state() |
    space_file_popularity_configuration_update_middleware_handler:state() |
    space_force_start_auto_storage_import_scan_create_middleware_handler:state() |
    space_force_stop_auto_storage_import_scan_create_middleware_handler:state() |
    space_instance_get_middleware_handler:state() |
    space_list_get_middleware_handler:state() |
    space_manual_storage_import_example_get_middleware_handler:state() |
    space_start_auto_cleaning_create_middleware_handler:state() |
    space_support_create_middleware_handler:state() |
    space_support_delete_middleware_handler:state() |
    space_support_update_middleware_handler:state() |
    storage_instance_delete_middleware_handler:state() |
    storage_instance_get_middleware_handler:state() |
    storage_instance_update_middleware_handler:state() |
    storage_instances_create_middleware_handler:state() |
    storage_list_get_middleware_handler:state() |
    storage_luma_acl_group_to_onedata_group_mapping_create_middleware_handler:state() |
    storage_luma_acl_group_to_onedata_group_mapping_delete_middleware_handler:state() |
    storage_luma_acl_group_to_onedata_group_mapping_get_middleware_handler:state() |
    storage_luma_acl_user_to_onedata_user_mapping_create_middleware_handler:state() |
    storage_luma_acl_user_to_onedata_user_mapping_delete_middleware_handler:state() |
    storage_luma_acl_user_to_onedata_user_mapping_get_middleware_handler:state() |
    storage_luma_configuration_get_middleware_handler:state() |
    storage_luma_db_delete_middleware_handler:state() |
    storage_luma_default_posix_credentials_create_middleware_handler:state() |
    storage_luma_default_posix_credentials_delete_middleware_handler:state() |
    storage_luma_default_posix_credentials_get_middleware_handler:state() |
    storage_luma_display_credentials_create_middleware_handler:state() |
    storage_luma_display_credentials_delete_middleware_handler:state() |
    storage_luma_display_credentials_get_middleware_handler:state() |
    storage_luma_onedata_user_to_credentials_mapping_create_middleware_handler:state() |
    storage_luma_onedata_user_to_credentials_mapping_delete_middleware_handler:state() |
    storage_luma_onedata_user_to_credentials_mapping_get_middleware_handler:state() |
    storage_luma_onedata_user_to_credentials_mapping_update_middleware_handler:state() |
    storage_luma_uid_to_onedata_user_mapping_create_middleware_handler:state() |
    storage_luma_uid_to_onedata_user_mapping_delete_middleware_handler:state() |
    storage_luma_uid_to_onedata_user_mapping_get_middleware_handler:state() |
    user_current_user_clusters_get_middleware_handler:state() |
    user_current_user_get_middleware_handler:state() |
    user_instance_create_middleware_handler:state() |
    user_instance_get_middleware_handler:state() |
    user_instance_update_middleware_handler:state() |
    user_list_get_middleware_handler:state() |
    zone_cluster_create_middleware_handler:state() |
    zone_cluster_get_middleware_handler:state() |
    zone_gui_message_get_middleware_handler:state() |
    zone_gui_message_update_middleware_handler:state() |
    zone_instance_get_middleware_handler:state() |
    zone_policies_get_middleware_handler:state() |
    zone_policies_update_middleware_handler:state().

-type output() ::
    cluster_current_cluster_get_middleware_handler:output() |
    cluster_current_cluster_members_summary_get_middleware_handler:output() |
    cluster_instance_get_middleware_handler:output() |
    cluster_invite_user_token_create_middleware_handler:output() |
    host_external_ips_get_middleware_handler:output() |
    host_external_ips_update_middleware_handler:output() |
    host_instance_create_middleware_handler:output() |
    host_instance_delete_middleware_handler:output() |
    host_instance_get_middleware_handler:output() |
    host_join_cluster_middleware_handler:output() |
    host_list_get_middleware_handler:output() |
    panel_configuration_get_middleware_handler:output() |
    panel_cookie_get_middleware_handler:output() |
    panel_dns_check_configuration_get_middleware_handler:output() |
    panel_dns_check_configuration_update_middleware_handler:output() |
    panel_dns_check_middleware_handler:output() |
    panel_emergency_passphrase_create_middleware_handler:output() |
    panel_emergency_passphrase_get_middleware_handler:output() |
    panel_health_get_middleware_handler:output() |
    panel_invite_token_create_middleware_handler:output() |
    panel_progress_get_middleware_handler:output() |
    panel_progress_update_middleware_handler:output() |
    panel_task_get_middleware_handler:output() |
    panel_test_image_get_middleware_handler:output() |
    panel_web_cert_get_middleware_handler:output() |
    panel_web_cert_update_middleware_handler:output() |
    provider_cluster_create_middleware_handler:output() |
    provider_cluster_get_middleware_handler:output() |
    provider_instance_create_middleware_handler:output() |
    provider_instance_delete_middleware_handler:output() |
    provider_instance_get_middleware_handler:output() |
    provider_instance_update_middleware_handler:output() |
    provider_remote_instance_get_middleware_handler:output() |
    provider_transfers_mock_get_middleware_handler:output() |
    provider_transfers_mock_update_middleware_handler:output() |
    service_cluster_manager_all_hosts_status_get_middleware_handler:output() |
    service_cluster_manager_host_status_get_middleware_handler:output() |
    service_cluster_manager_instances_create_middleware_handler:output() |
    service_cluster_manager_start_stop_all_update_middleware_handler:output() |
    service_cluster_manager_start_stop_update_middleware_handler:output() |
    service_couchbase_all_hosts_status_get_middleware_handler:output() |
    service_couchbase_host_status_get_middleware_handler:output() |
    service_couchbase_instances_create_middleware_handler:output() |
    service_couchbase_start_stop_all_update_middleware_handler:output() |
    service_couchbase_start_stop_update_middleware_handler:output() |
    service_ones3_all_hosts_status_get_middleware_handler:output() |
    service_ones3_host_status_get_middleware_handler:output() |
    service_ones3_instances_create_middleware_handler:output() |
    service_ones3_start_stop_all_update_middleware_handler:output() |
    service_ones3_start_stop_update_middleware_handler:output() |
    service_op_worker_all_hosts_status_get_middleware_handler:output() |
    service_op_worker_host_status_get_middleware_handler:output() |
    service_op_worker_instances_create_middleware_handler:output() |
    service_op_worker_nagios_get_middleware_handler:output() |
    service_op_worker_start_stop_all_update_middleware_handler:output() |
    service_op_worker_start_stop_update_middleware_handler:output() |
    service_oz_worker_all_hosts_status_get_middleware_handler:output() |
    service_oz_worker_host_status_get_middleware_handler:output() |
    service_oz_worker_instances_create_middleware_handler:output() |
    service_oz_worker_nagios_get_middleware_handler:output() |
    service_oz_worker_start_stop_all_update_middleware_handler:output() |
    service_oz_worker_start_stop_update_middleware_handler:output() |
    space_auto_cleaning_configuration_get_middleware_handler:output() |
    space_auto_cleaning_configuration_update_middleware_handler:output() |
    space_auto_cleaning_report_get_middleware_handler:output() |
    space_auto_cleaning_reports_list_get_middleware_handler:output() |
    space_auto_cleaning_status_get_middleware_handler:output() |
    space_auto_storage_import_info_get_middleware_handler:output() |
    space_auto_storage_import_stats_get_middleware_handler:output() |
    space_cancel_auto_cleaning_create_middleware_handler:output() |
    space_file_popularity_configuration_get_middleware_handler:output() |
    space_file_popularity_configuration_update_middleware_handler:output() |
    space_force_start_auto_storage_import_scan_create_middleware_handler:output() |
    space_force_stop_auto_storage_import_scan_create_middleware_handler:output() |
    space_instance_get_middleware_handler:output() |
    space_list_get_middleware_handler:output() |
    space_manual_storage_import_example_get_middleware_handler:output() |
    space_start_auto_cleaning_create_middleware_handler:output() |
    space_support_create_middleware_handler:output() |
    space_support_delete_middleware_handler:output() |
    space_support_update_middleware_handler:output() |
    storage_instance_delete_middleware_handler:output() |
    storage_instance_get_middleware_handler:output() |
    storage_instance_update_middleware_handler:output() |
    storage_instances_create_middleware_handler:output() |
    storage_list_get_middleware_handler:output() |
    storage_luma_acl_group_to_onedata_group_mapping_create_middleware_handler:output() |
    storage_luma_acl_group_to_onedata_group_mapping_delete_middleware_handler:output() |
    storage_luma_acl_group_to_onedata_group_mapping_get_middleware_handler:output() |
    storage_luma_acl_user_to_onedata_user_mapping_create_middleware_handler:output() |
    storage_luma_acl_user_to_onedata_user_mapping_delete_middleware_handler:output() |
    storage_luma_acl_user_to_onedata_user_mapping_get_middleware_handler:output() |
    storage_luma_configuration_get_middleware_handler:output() |
    storage_luma_db_delete_middleware_handler:output() |
    storage_luma_default_posix_credentials_create_middleware_handler:output() |
    storage_luma_default_posix_credentials_delete_middleware_handler:output() |
    storage_luma_default_posix_credentials_get_middleware_handler:output() |
    storage_luma_display_credentials_create_middleware_handler:output() |
    storage_luma_display_credentials_delete_middleware_handler:output() |
    storage_luma_display_credentials_get_middleware_handler:output() |
    storage_luma_onedata_user_to_credentials_mapping_create_middleware_handler:output() |
    storage_luma_onedata_user_to_credentials_mapping_delete_middleware_handler:output() |
    storage_luma_onedata_user_to_credentials_mapping_get_middleware_handler:output() |
    storage_luma_onedata_user_to_credentials_mapping_update_middleware_handler:output() |
    storage_luma_uid_to_onedata_user_mapping_create_middleware_handler:output() |
    storage_luma_uid_to_onedata_user_mapping_delete_middleware_handler:output() |
    storage_luma_uid_to_onedata_user_mapping_get_middleware_handler:output() |
    user_current_user_clusters_get_middleware_handler:output() |
    user_current_user_get_middleware_handler:output() |
    user_instance_create_middleware_handler:output() |
    user_instance_get_middleware_handler:output() |
    user_instance_update_middleware_handler:output() |
    user_list_get_middleware_handler:output() |
    zone_cluster_create_middleware_handler:output() |
    zone_cluster_get_middleware_handler:output() |
    zone_gui_message_get_middleware_handler:output() |
    zone_gui_message_update_middleware_handler:output() |
    zone_instance_get_middleware_handler:output() |
    zone_policies_get_middleware_handler:output() |
    zone_policies_update_middleware_handler:output().

-export_type([t/0, input/0, state/0, output/0]).
