#!/bin/sh
#
# chkconfig: 2345 80 30
# description: Onepanel service

### BEGIN INIT INFO
# Provides:		    onepanel_init
# Required-Start:	$local_fs $remote_fs $network $time
# Required-Stop:	$local_fs $remote_fs $network $time
# Should-Start:		$syslog
# Should-Stop:		$syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Onepanel service
# Description:	Manages Onepanel node that is configured on this machine.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# Needed for erlexec to run
export HOME=/

# Default installation path
PREFIX=/opt/veil/files/onepanel_node

start() {
	${PREFIX}/bin/onepanel ping > /dev/null 2>&1 ; status=$?
	if [ $status -eq 1 ]; then
		echo -n "Starting onepanel: "
		${PREFIX}/bin/onepanel start > /dev/null 2>&1
		ret=$?
		[ $ret -eq 0 ] && success || failure
		echo
		return $ret
	fi
}

stop() {
	${PREFIX}/bin/onepanel ping > /dev/null 2>&1 ; status=$?
	if [ $status -eq 0 ]; then
		echo -n "Stopping onepanel: "
		${PREFIX}/bin/onepanel stop > /dev/null 2>&1
		ret=$?
		[ $ret -eq 0 ] && success || failure
		echo
		return $ret
	fi
}

restart() {
	stop
	start
}

status() {
	${PREFIX}/bin/onepanel ping > /dev/null 2>&1 ; status=$?
	echo -n "onepanel: "
	if [ $status -eq 0 ]; then
		 echo "Running."
		 return 0
	else
		echo "Not running."
		return 3
	fi
}

case "$1" in
    start)
		# Execute function and create a lock file (required by red-hat based systems)
		$1 && touch /var/lock/subsys/onepanel
		;;

	restart|force-reload)
		restart && touch /var/lock/subsys/onepanel
		;;

    stop)
		$1
		status || rm -f /var/lock/subsys/onepanel
		;;

	status)
		$1
		;;

    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}"
        exit 1
		;;
esac

exit $?
